/** Declaration file generated by dts-gen */

export function clear(key: string): void;

export function clearGlobal(key: string): void;

export function get<T>(key: string): T;

export function getValueStackCopy(): Object;

export function pop(): void;

export function push(values: Object): void;

export function pushArgv(): void;

export function pushEnv(): void;

export function pushJsonFile(filePath: string): void;

export function set<T>(key: string, value: T): void;

export function setGlobal<T>(key: string, value: T): void;

export function toObject(): Object;
